# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: win-64
anyio=4.10.0=pyhe01879c_0
argon2-cffi=25.1.0=pyhd8ed1ab_0
argon2-cffi-bindings=21.2.0=py312h827c3e9_1
asttokens=2.4.0=pypi_0
async-lru=2.0.5=pyh29332c3_0
attrs=24.2.0=py312haa95532_0
babel=2.17.0=pyhd8ed1ab_0
backcall=0.2.0=pypi_0
beautifulsoup4=4.12.2=py312haa95532_0
blas=1.0=mkl
bleach=6.2.0=py312haa95532_0
bottleneck=1.3.5=py312he558020_0
brotli-python=1.0.9=py312hd77b12b_7
bs4=4.12.2=py38hd3eb1b0_0
bzip2=1.0.8=he774522_0
ca-certificates=2025.9.9=haa95532_0
certifi=2025.8.3=py312haa95532_0
cffi=1.16.0=py312h2bbff1b_0
charset-normalizer=2.0.4=pyhd3eb1b0_0
colorama=0.4.6=pyhd8ed1ab_1
comm=0.1.4=pypi_0
contourpy=1.2.1=pypi_0
cryptography=41.0.7=py312h89fc84f_0
cycler=0.12.1=pypi_0
debugpy=1.8.0=pypi_0
decorator=5.1.1=pypi_0
defusedxml=0.7.1=pyhd3eb1b0_0
distro=1.9.0=pypi_0
et-xmlfile=1.1.0=pypi_0
exceptiongroup=1.3.0=pyhd8ed1ab_0
executing=2.0.0=pypi_0
expat=2.5.0=hd77b12b_0
fastjsonschema=2.21.0=pypi_0
fire=0.6.0=pypi_0
fonttools=4.51.0=pypi_0
greenlet=3.0.1=py312hd77b12b_0
h11=0.16.0=pyhd8ed1ab_0
h2=4.2.0=pyhd8ed1ab_0
hpack=4.1.0=pyhd8ed1ab_0
html5lib=1.1=pyhd3eb1b0_0
httpcore=1.0.9=pyh29332c3_0
httpx=0.28.1=pyhd8ed1ab_0
hyperframe=6.1.0=pyhd8ed1ab_0
idna=3.4=py312haa95532_0
importlib-metadata=8.7.0=pyhe01879c_1
intel-openmp=2023.1.0=h59b6b97_46320
ipykernel=6.26.0=pypi_0
ipython=8.16.1=pypi_0
ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
ipywidgets=8.1.3=pypi_0
jedi=0.19.1=pypi_0
jinja2=3.1.4=py312haa95532_1
jpype1=1.5.0=pypi_0
json5=0.12.1=pyhd8ed1ab_0
jsonschema=4.23.0=py312haa95532_0
jsonschema-specifications=2024.10.1=pypi_0
jupyter-client=8.5.0=pypi_0
jupyter-core=5.4.0=pypi_0
jupyter-lsp=2.2.6=pyhe01879c_0
jupyter_client=8.6.0=py312haa95532_0
jupyter_core=5.7.2=py312haa95532_0
jupyter_events=0.12.0=py312haa95532_0
jupyter_server=2.16.0=pyhe01879c_0
jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
jupyterlab=4.4.5=pyhd8ed1ab_0
jupyterlab-widgets=3.0.11=pypi_0
jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
jupyterlab_server=2.27.3=pyhd8ed1ab_1
kiwisolver=1.4.5=pypi_0
krb5=1.20.1=h5b6d351_0
libffi=3.4.4=hd77b12b_0
libiconv=1.16=h2bbff1b_2
libpq=12.17=h906ac69_0
libsodium=1.0.18=h62dcd97_0
libxml2=2.10.4=h0ad7f3c_1
libxslt=1.1.37=h2bbff1b_1
lxml=4.9.3=py312h09808a7_0
markupsafe=3.0.2=pypi_0
matplotlib=3.8.4=pypi_0
matplotlib-inline=0.1.6=pypi_0
mistune=2.0.3=pypi_0
mkl=2023.1.0=h6b88ed4_46358
mkl-service=2.4.0=py312h2bbff1b_1
mkl_fft=1.3.8=py312h2bbff1b_0
mkl_random=1.2.4=py312h59b6b97_0
nbclient=0.10.1=pypi_0
nbconvert=7.16.6=py312haa95532_0
nbconvert-core=7.16.6=py312haa95532_0
nbconvert-pandoc=7.16.6=py312haa95532_0
nbformat=5.10.4=py312haa95532_0
nest-asyncio=1.5.8=pypi_0
notebook=7.4.5=pyhd8ed1ab_0
notebook-shim=0.2.4=pyhd8ed1ab_1
numexpr=2.8.7=py312h96b7d27_0
numpy=1.26.3=py312hfd52020_0
numpy-base=1.26.3=py312h4dde369_0
openpyxl=3.1.4=pypi_0
openssl=3.0.16=h3f729d1_0
outcome=1.3.0.post0=pypi_0
overrides=7.7.0=pyhd8ed1ab_1
packaging=23.2=pypi_0
pandas=2.1.4=py312hc7c4135_0
pandoc=3.7.0.2=h57928b3_0
pandocfilters=1.5.1=pypi_0
parso=0.8.3=pypi_0
patsy=0.5.6=pypi_0
pdfminer-six=20221105=pypi_0
pdfplumber=0.10.4=pypi_0
pickleshare=0.7.5=pyhd8ed1ab_1004
pillow=10.2.0=pypi_0
pip=25.2=pypi_0
platformdirs=3.11.0=pypi_0
prometheus_client=0.22.1=pyhd8ed1ab_0
prompt-toolkit=3.0.39=pypi_0
psutil=5.9.6=pypi_0
psycopg2=2.9.9=py312h2bbff1b_0
pure-eval=0.2.2=pypi_0
pure_eval=0.2.3=pyhd8ed1ab_1
pycparser=2.21=pyhd3eb1b0_0
pygame=2.5.2=pypi_0
pygments=2.16.1=pypi_0
pymupdf=1.23.26=pypi_0
pymupdfb=1.23.22=pypi_0
pyopenssl=23.2.0=py312haa95532_0
pyparsing=3.1.2=pypi_0
pypdf2=3.0.1=py312haa95532_0
pypdfium2=4.27.0=pypi_0
pysocks=1.7.1=py312haa95532_0
python=3.12.1=h1d929f7_0
python-dateutil=2.8.2=pyhd3eb1b0_0
python-docx=1.1.0=pypi_0
python-dotenv=1.0.1=pypi_0
python-fastjsonschema=2.20.0=py312haa95532_0
python-json-logger=2.0.7=pyhd8ed1ab_0
python-tzdata=2023.3=pyhd3eb1b0_0
pytz=2023.3.post1=py312haa95532_0
pywin32=306=pypi_0
pywinpty=2.0.15=py312h72d21ff_0
pyyaml=6.0.2=py312h827c3e9_0
pyzmq=25.1.1=pypi_0
referencing=0.35.1=pypi_0
requests=2.31.0=py312haa95532_1
rfc3339-validator=0.1.4=pyhd8ed1ab_1
rfc3986-validator=0.1.1=pyh9f0ad1d_0
roman=4.1=pypi_0
rpds-py=0.21.0=pypi_0
scipy=1.14.1=pypi_0
seaborn=0.13.2=pypi_0
selenium=4.35.0=pypi_0
send2trash=1.8.3=pyh5737063_1
setuptools=68.2.2=py312haa95532_0
six=1.16.0=pyhd3eb1b0_1
sniffio=1.3.1=pyhd8ed1ab_1
sortedcontainers=2.4.0=pypi_0
soupsieve=2.5=py312haa95532_0
sqlalchemy=2.0.25=py312h2bbff1b_0
sqlite=3.41.2=h2bbff1b_0
stack_data=0.6.3=pyhd8ed1ab_1
statsmodels=0.14.3=pypi_0
tabula=1.0.5=pypi_0
tabula-py=2.9.0=pypi_0
tbb=2021.8.0=h59b6b97_0
termcolor=2.4.0=pypi_0
terminado=0.18.1=pyh5737063_0
tinycss2=1.4.0=pypi_0
tk=8.6.12=h2bbff1b_0
tomli=2.2.1=pyhe01879c_2
tornado=6.3.3=pypi_0
tqdm=4.67.1=py312hfc267ef_0
traitlets=5.12.0=pypi_0
trio=0.30.0=pypi_0
trio-websocket=0.12.2=pypi_0
typing-extensions=4.14.1=pypi_0
typing_utils=0.1.0=pyhd8ed1ab_1
tzdata=2023d=h04d1e81_0
unidecode=1.3.8=pypi_0
urllib3=2.5.0=pypi_0
vc=14.2=h21ff451_1
vs2015_runtime=14.40.33807=h98bb1dd_1
wcwidth=0.2.8=pypi_0
webdriver-manager=4.0.2=pypi_0
webencodings=0.5.1=py312haa95532_2
websocket-client=1.8.0=pyhd8ed1ab_1
wheel=0.41.2=py312haa95532_0
widgetsnbextension=4.0.11=pypi_0
win_inet_pton=1.1.0=py312haa95532_0
winpty=0.4.3=4
wsproto=1.2.0=pypi_0
xz=5.4.5=h8cc25b3_0
yaml=0.2.5=h8ffe710_2
zeromq=4.3.5=hd77b12b_0
zipp=3.23.0=pyhd8ed1ab_0
zlib=1.2.13=h8cc25b3_0
